"""questions table added and indexing

Revision ID: 05c1186cbb88
Revises: bec68dbf780b
Create Date: 2026-06-22 18:57:28.302339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c1186cbb88'
down_revision: Union[str, Sequence[str], None] = 'bec68dbf780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audio_responses_session_id'), 'audio_responses', ['session_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_audio_responses_session_id'), table_name='audio_responses')
    # ### end Alembic commands ###
