"""added new column t session_summary

Revision ID: 2c6b6d94cf78
Revises: e52e7dfde50d
Create Date: 2026-06-25 16:11:34.158710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6b6d94cf78'
down_revision: Union[str, Sequence[str], None] = 'e52e7dfde50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_summaries', sa.Column('avg_score_situational', sa.Numeric(precision=3, scale=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_summaries', 'avg_score_situational')
    # ### end Alembic commands ###
