"""revised schema for session

Revision ID: 3f14cd826c15
Revises: 52a896213206
Create Date: 2026-06-22 19:04:37.108590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f14cd826c15'
down_revision: Union[str, Sequence[str], None] = '52a896213206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
import sqlalchemy as sa




def upgrade():
    experiencelevel = sa.Enum(
        'intern', 'junior', 'mid', 'senior', 'lead',
        name='experiencelevel'
    )

    experiencelevel.create(op.get_bind())

    op.add_column(
        'interview_sessions',
        sa.Column('role', sa.Text(), nullable=True)
    )

    op.add_column(
        'interview_sessions',
        sa.Column('level', experiencelevel, nullable=True)
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'level')
    op.drop_column('interview_sessions', 'role')
    # ### end Alembic commands ###
