"""Add voice_outputs table

Revision ID: 934252819324
Revises: 2c6b6d94cf78
Create Date: 2026-06-26 14:16:13.674125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934252819324'
down_revision: Union[str, Sequence[str], None] = '2c6b6d94cf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=False),
    sa.Column('voice_model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['answer_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_outputs_evaluation_id'), 'voice_outputs', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_voice_outputs_question_id'), 'voice_outputs', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_outputs_question_id'), table_name='voice_outputs')
    op.drop_index(op.f('ix_voice_outputs_evaluation_id'), table_name='voice_outputs')
    op.drop_table('voice_outputs')
    # ### end Alembic commands ###
