"""session summary table and user progress table

Revision ID: e52e7dfde50d
Revises: f95487c8efd9
Create Date: 2026-06-25 15:20:08.297848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52e7dfde50d'
down_revision: Union[str, Sequence[str], None] = 'f95487c8efd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('interviews_completed', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('best_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=True)
    op.create_table('session_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('avg_score_behavioral', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('avg_score_technical', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('highest_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('lowest_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_summaries_session_id'), 'session_summaries', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_summaries_session_id'), table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    # ### end Alembic commands ###
