"""session summary table and user progress table

Revision ID: f95487c8efd9
Revises: 92ecc58fc939
Create Date: 2026-06-25 15:12:43.597511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95487c8efd9'
down_revision: Union[str, Sequence[str], None] = '92ecc58fc939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE interview_sessions SET status = 'inprogress' WHERE status IS NULL")
    op.alter_column('interview_sessions', 'status',
               existing_type=postgresql.ENUM('complete', 'inprogress', name='status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_sessions', 'status',
               existing_type=postgresql.ENUM('complete', 'inprogress', name='status'),
               nullable=True)
    # ### end Alembic commands ###
